{{- if .Values.Secure.Enabled }}
{{- if .Values.Secure.ServiceAccount.Create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cockroachdb.serviceAccountName" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
{{- if not .Values.Secure.BringYourOwnCert.Enabled }}
  - create
{{- end }}
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
subjects:
- kind: ServiceAccount
  name: {{ template "cockroachdb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
{{- if not .Values.Secure.BringYourOwnCert.Enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
subjects:
- kind: ServiceAccount
  name: {{ template "cockroachdb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
---
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}-public"
  annotations:
{{ toYaml .Values.Service.annotations | indent 4 }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  type: {{ .Values.Service.type }}
  ports:
  # The main port, served by gRPC, serves Postgres-flavor SQL, internode
  # traffic and the cli.
  - port: {{ .Values.ExternalGrpcPort }}
    targetPort: {{ .Values.InternalGrpcPort }}
    name: {{ .Values.ExternalGrpcName }}
  # The secondary port serves the UI as well as health and debug endpoints.
  - port: {{ .Values.ExternalHttpPort }}
    targetPort: {{ .Values.InternalHttpPort }}
    name: {{ .Values.HttpName }}
    {{- if ne .Values.InternalGrpcPort .Values.ExternalGrpcPort }}
  - port: {{ .Values.InternalGrpcPort }}
    targetPort: {{ .Values.InternalGrpcPort }}
    name: {{ .Values.InternalGrpcName }}
    {{- end }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
---
apiVersion: v1
kind: Service
metadata:
  # This service only exists to create DNS entries for each pod in the stateful
  # set such that they can resolve each other's IP addresses. It does not
  # create a load-balanced ClusterIP and should not be used directly by clients
  # in most circumstances.
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
  annotations:
    # Use this annotation in addition to the actual field below because the
    # annotation will stop being respected soon but the field is broken in
    # some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
{{- if .Values.PrometheusScraper.Enabled }}
    prometheus.io/scrape: "true"
{{- else }}
    prometheus.io/scrape: "false"
{{- end }}
    prometheus.io/path: "_status/vars"
{{- if .Values.Secure.Enabled }}    
    prometheus.io/scheme: "https"
{{- else }}
    prometheus.io/scheme: "http"
{{- end }}
    prometheus.io/port: "{{ .Values.ExternalHttpPort }}"
spec:
  ports:
  - port: {{ .Values.ExternalGrpcPort }}
    targetPort: {{ .Values.InternalGrpcPort }}
    name: {{ .Values.ExternalGrpcName }}
  # The secondary port serves the UI as well as health and debug endpoints.
  - port: {{ .Values.ExternalHttpPort }}
    targetPort: {{ .Values.InternalHttpPort }}
    name: {{ .Values.HttpName }}
    {{- if ne .Values.InternalGrpcPort .Values.ExternalGrpcPort }}
  - port: {{ .Values.InternalGrpcPort }}
    targetPort: {{ .Values.InternalGrpcPort }}
    name: {{ .Values.InternalGrpcName }}
    {{- end }}
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other CockroachDB pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}-budget"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
spec:
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Component }}"
  maxUnavailable: {{ .Values.MaxUnavailable }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
spec:
  serviceName: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
  replicas: {{ default 3 .Values.Replicas }}
  selector:
    matchLabels:
      heritage: {{ .Release.Service | quote }}
      release: {{ .Release.Name | quote }}
      component: "{{ .Release.Name }}-{{ .Values.Component }}"
  template:
    metadata:
{{- if .Values.ExtraAnnotations }}
      annotations:
{{ toYaml .Values.ExtraAnnotations | indent 8 }}
{{- end }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Component }}"
    spec:
{{- if .Values.HostNetwork.Enabled }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
{{- if .Values.Secure.Enabled }}
      serviceAccountName: {{ template "cockroachdb.serviceAccountName" . }}
{{- end }}
      initContainers:
{{- if .Values.LocalityInjection.Enabled }}
      - name: inject-locality
        image: "{{ .Values.LocalityInjection.Image }}"
        imagePullPolicy: "{{ .Values.LocalityInjection.ImagePullPolicy }}"
        command:
        {{- range .Values.LocalityInjection.Commands }}
        - {{ . | quote }}
        {{- end }}
        volumeMounts:
        - name: locality-config
          mountPath: /locality-config
        - name: injection
          mountPath: /injection
{{- end }}
{{- if .Values.Secure.Enabled }}
{{- if not .Values.Secure.BringYourOwnCert.Enabled }}
      # The init-certs container sends a certificate signing request to the
      # kubernetes cluster.
      # You can see pending requests using: kubectl get csr
      # CSRs can be approved using:         kubectl certificate approve <csr name>
      #
      # All addresses used to contact a node must be specified in the --addresses arg.
      #
      # In addition to the node certificate and key, the init-certs entrypoint will symlink
      # the cluster CA to the certs directory.
      - name: init-certs
        image: "{{ .Values.Secure.RequestCertsImage }}:{{ .Values.Secure.RequestCertsImageTag }}"
        imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
        command:
        - "/bin/ash"
        - "-ecx"
        - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=node -addresses=localhost,127.0.0.1,${NODE_NAME},$(hostname -f),{{ if .Values.HostNetwork.Enabled }}{{ if .Values.NodeAlias.Enabled }}$(cat /nodeAlias){{ else }}${NODE_NAME}{{ end }}{{ if .Values.MultiNetwork.Enabled }}.{{ .Values.MultiNetwork.PublicDomain }},{{ end }}{{ end }}$(hostname -f|cut -f 1-2 -d '.'),{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}-public,{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}-public.$(hostname -f|cut -f 3- -d '.') -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: certs
          mountPath: /cockroach-certs
{{- if .Values.NodeAlias.Enabled }}          
        - name: node-alias
          mountPath: /nodeAlias
          readOnly: true
{{- end }}
{{- end }}
{{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - "{{ .Release.Name }}-{{ .Values.Component }}"
              topologyKey: kubernetes.io/hostname
      {{- if .Values.NodeSelector }}
      nodeSelector:
{{ toYaml .Values.NodeSelector | indent 8 }}
      {{- end }}
{{- if .Values.Tolerations }}
      tolerations:
{{ toYaml .Values.Tolerations | indent 8 }}
{{- end }}
      containers:
      - name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
        image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
        imagePullPolicy: "{{ .Values.ImagePullPolicy }}"
        ports:
        - containerPort: {{ .Values.InternalGrpcPort }}
          name: grpc
        - containerPort: {{ .Values.InternalHttpPort }}
          name: http
        livenessProbe:
          httpGet:
            path: "/health"
            port: http
{{- if .Values.Secure.Enabled }}
            scheme: HTTPS
{{- end }}
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/health?ready=1"
            port: http
{{- if .Values.Secure.Enabled }}
            scheme: HTTPS
{{- end }}
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        resources:
{{ toYaml .Values.Resources | indent 10 }}
        env:
        - name: STATEFULSET_NAME
          value: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}"
        - name: STATEFULSET_FQDN
          value: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 56 }}.{{ .Release.Namespace }}.svc.{{ .Values.ClusterDomain }}"
        - name: COCKROACH_CHANNEL
          value: kubernetes-helm
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{{- if .Values.ExtraEnvArgs }}
{{ toYaml .Values.ExtraEnvArgs | indent 8 }}
{{- end }}
        volumeMounts:
{{- if .Values.NodeAlias.Enabled }}          
        - name: node-alias
          mountPath: /nodeAlias
          readOnly: true
{{- end }}
{{- if .Values.LocalityInjection.Enabled }}
        - name: injection
          mountPath: /injection
{{- end }}
        - name: datadir
          mountPath: /cockroach/cockroach-data
{{- if .Values.Secure.Enabled }}
        - name: certs
          mountPath: /cockroach/cockroach-certs
{{- end }}
{{- range .Values.ExtraSecretMounts }}
        - name: extra-secret-{{ . }}
          mountPath: /etc/cockroach/secrets/{{ . }}
          readOnly: true
{{- end }}
        command:
          - "/bin/bash"
          - "-ecx"
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.
          - "{{ if .Values.LocalityInjection.Enabled }}source /injection/locality-injection && echo $LOCALITY && {{ end }}exec /cockroach/cockroach start --logtostderr {{ if .Values.Secure.Enabled }}--certs-dir /cockroach/cockroach-certs{{ else }}--insecure{{ end }} --advertise-addr {{ if .Values.HostNetwork.Enabled }}{{ if .Values.NodeAlias.Enabled }}$(cat /nodeAlias){{ else }}${NODE_NAME}{{ end }}{{ if .Values.MultiNetwork.Enabled }}.{{ .Values.MultiNetwork.PublicDomain }}{{ end }}{{ else }}$(hostname).${STATEFULSET_FQDN}{{ end }} {{ if .Values.MultiNetwork.Enabled }}--locality-advertise-addr {{ .Values.MultiNetwork.LocalityTag }}@${NODE_NAME}{{ end }} --http-addr 0.0.0.0 --http-port {{ .Values.InternalHttpPort }} --port {{ .Values.InternalGrpcPort }} --cache {{ .Values.CacheSize }} --max-sql-memory {{ .Values.MaxSQLMemory }} {{ if .Values.Locality }}--locality={{ if .Values.LocalityInjection.Enabled }}$(LOCALITY){{ end }}{{.Values.Locality }}{{ end }} --join {{ if .Values.JoinExisting }}{{ join "," .Values.JoinExisting }}{{ else }}${STATEFULSET_NAME}-0.${STATEFULSET_FQDN}:{{ .Values.InternalGrpcPort }},${STATEFULSET_NAME}-1.${STATEFULSET_FQDN}:{{ .Values.InternalGrpcPort }},${STATEFULSET_NAME}-2.${STATEFULSET_FQDN}:{{ .Values.InternalGrpcPort }}{{ end }}{{ range .Values.ExtraArgs }} {{ . }}{{ end }}"
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      volumes:
{{- if .Values.NodeAlias.Enabled }}
      - name: node-alias
        hostPath:
          path: {{ .Values.NodeAlias.FilePath }}
          type: File
{{- end }}      
{{- if .Values.LocalityInjection.Enabled }}
      # load locality-injection config from configmap    
      - name: locality-config
        configMap:
          name: "{{ printf "%s-%s-locality-config" .Release.Name .Values.Name | trunc 56 }}"
      # share rendered config to main container
      - name: injection
        emptyDir:
          medium: Memory
{{- end }}
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
{{- if .Values.Secure.Enabled }}
      - name: certs
{{- if .Values.Secure.BringYourOwnCert.Enabled }}
        secret:
          secretName: {{ .Values.Secure.BringYourOwnCert.NodeCertName }}
          defaultMode: 256
{{- else }}
        emptyDir: {}
{{- end }}
{{- end }}
{{- range .Values.ExtraSecretMounts }}
      - name: extra-secret-{{ . }}
        secret:
          secretName: {{ . }}
{{- end }}
  podManagementPolicy: {{ .Values.PodManagementPolicy }}
  updateStrategy:
{{ toYaml .Values.UpdateStrategy | indent 4 }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
{{- if .Values.StorageClass }}
{{- if (eq "-" .Values.StorageClass) }}
      storageClassName: ""
{{- else }}
      storageClassName: "{{ .Values.StorageClass }}"
{{- end }}
{{- end }}
      resources:
        requests:
          storage: "{{ .Values.Storage }}"
